GeneralManager:
  #config_folder: '/home/jsaraydaryan/ros_robotcupathome_ws/src/data/general_management'
  config_folder: '/home/student/Bureau/workspace_palbator_dev/src/HriManager/scripts/templates/public/json/receptionist/'
  all_scenarios:
    - 'COCKTAIL_PARTY'
    - 'TEST_NAVIG'
    - 'DOOR_OPENED_NAVIG'
    - 'TEST_DIALOGUE'
    - 'TEST_COCKTAIL_PARTY_V3'
    - 'TEST_COCKTAIL_PARTY_V2'
    - 'TEST_HOOMANO'
    - 'SPRV1'
    - 'SPRV2'
    - 'INSPECTION'
    - 'GPRSV1'
    - 'GPRSV2CPE'
    - 'GARBAGE_2019V2_CPE'
    - 'RECEPTIONIST_2019_CPE'
    - 'TEST_FACE_LEARN_AND_FIND_POINT'
    - 'INSPECTION_2019'
    - 'RECEPTIONIST_2020_CPE'
  current_scenario: 'RECEPTIONIST_2020_CPE' # Must be in the "scenarios" list above
